// All mission text: speakers, dialogue, objectives, hints and cards (Hebrew, RTL).
// Rewrite the story here; the mission script (mission1.js) only refers to these ids.
// Placeholder dialogue: to be rewritten.

export const SPEAKERS = {
  cmd: { name: 'סמ״ר אלון', color: '#e2cf9c' }, // squad commander
  yonatan: { name: 'יונתן', color: '#9fd0a8' },
  noam: { name: 'נועם', color: '#9fc2ff' },
  me: { name: 'אני', color: '#f2f2f2' }, // the player
  radio: { name: 'קשר', color: '#ffb36b', radio: true },
  control: { name: 'מוקד', color: '#ffb36b', radio: true },
  post3: { name: 'תצפית 3', color: '#ffb36b', radio: true },
  cmdRadio: { name: 'סמ״ר אלון (קשר)', color: '#e2cf9c', radio: true },
  noamRadio: { name: 'נועם (קשר)', color: '#9fc2ff', radio: true },
  meRadio: { name: 'אני (קשר)', color: '#f2f2f2', radio: true },
  guard: { name: 'שמעון, מאבטח', color: '#b9c7de' },
  guide: { name: 'מדריכת טיולים', color: '#d8c7f0' },
  civilian: { name: 'אזרח', color: '#d9d9d9' },
  civilianWoman: { name: 'אזרחית', color: '#d9d9d9' },
  // The Selichot crowd (story/people.js: who speaks for each kind of person).
  man: { name: 'מתפלל', color: '#d9d9d9' },
  woman: { name: 'מתפללת', color: '#d9d9d9' },
  visitor: { name: 'מבקר', color: '#d9d9d9' },
  visitorF: { name: 'מבקרת', color: '#d9d9d9' },
  dad: { name: 'אבא', color: '#d9d9d9' },
  mom: { name: 'אמא', color: '#d9d9d9' },
  elder: { name: 'סבא', color: '#e6dcc6' },
  grandma: { name: 'סבתא', color: '#e6dcc6' },
  kid: { name: 'ילד', color: '#f0e0a0' },
  kidGirl: { name: 'ילדה', color: '#f0e0a0' },
  teen: { name: 'נער', color: '#d9d9d9' },
  tourist: { name: 'תייר', color: '#c8e0d0' },
  touristWoman: { name: 'תיירת', color: '#c8e0d0' },
  yeshiva: { name: 'בחור ישיבה', color: '#d9d9d9' },
  usher: { name: 'סדרן', color: '#f0c890' },
  collector: { name: 'גבאי צדקה', color: '#d9d9d9' },
  soldierVisitor: { name: 'חייל', color: '#b8c8a0' },
  police: { name: 'שוטר מג״ב', color: '#a8c0a8' },
};

export const LINES = {
  // ---- Part 1: the night of Selichot ----
  // Task 1: the security checkpoint at the southern entrance.
  cp_brief_1: { speaker: 'yonatan', text: 'אז ככה: הלילה סליחות אחרונות לפני כיפור. הלילה הכי עמוס בשנה, עשרות אלפים יגיעו עד חצות.' },
  cp_brief_2: { speaker: 'yonatan', text: 'בגלל זה שלחו אותנו לתגבר את המאבטחים בבידוק. אני מכניס אותם לתור, אתה על המסך והגלאי.' },
  cp_brief_3: { speaker: 'yonatan', text: 'תסתכל על מסך השיקוף. אם משהו נראה מוזר, פותחים את התיק. צפצף בשער? גלאי ידני. ואז מכניסים, או עוצרים.' },
  cp_next: { speaker: 'yonatan', text: 'הבא בתור, בבקשה!' },
  cp_ok_1: { speaker: 'yonatan', text: 'יופי. הבא.' },
  cp_ok_2: { speaker: 'yonatan', text: 'סבבה, ממשיכים.' },
  cp_need_open: { speaker: 'yonatan', text: 'רגע! ראית את המסך? יש שם משהו מתכתי וארוך. תפתח את התיק.' },
  cp_need_wand: { speaker: 'yonatan', text: 'רגע, השער צפצף. תעביר עליו גלאי ידני קודם.' },
  cp_need_take: { speaker: 'yonatan', text: 'הסכין לא נכנסת פנימה. תחרים אותה (F), הוא יקבל אותה ביציאה.' },
  cp_no_stop: { speaker: 'yonatan', text: 'על מה לעצור אותו? הכול נקי. תכניס.' },
  cp_unopened: { speaker: 'yonatan', text: 'לא פתחת? טוב, לפי המסך זה קוגל. נראה לי שנשרוד.' },

  cp_haredi_1: { speaker: 'man', text: 'ערב טוב, גמר חתימה טובה. רק סידור וטלית, כמו כל שנה.' },
  cp_haredi_in: { speaker: 'man', text: 'תודה, תודה. שאלוקים ישמור עליכם.' },
  cp_teen_1: { speaker: 'teen', text: 'אחי, מהר בבקשה, החבר׳ה שלי כבר בפנים!' },
  cp_teen_wand: { speaker: 'teen', text: 'זה המפתחות! אמרתי לך, רק המפתחות.' },
  cp_teen_in: { speaker: 'teen', text: 'תודה אחי! גמר טוב!' },
  cp_grandma_1: { speaker: 'grandma', text: 'שלום חמודים. זה רק קצת אוכל לנכדים, הם מחכים לי ליד הקיר.' },
  cp_grandma_open: { speaker: 'grandma', text: 'קוגל, רוגלך, פיתות ותרמוס. קח רוגלך, קח! אתה רזה מדי.' },
  cp_grandma_me: { speaker: 'me', text: 'תודה, סבתא. אני במשמרת...' },
  cp_grandma_2: { speaker: 'grandma', text: 'במשמרת אוכלים יותר! גמר חתימה טובה, חמודים.' },
  cp_tourist_1: { speaker: 'tourist', text: 'Hi! Is this the line for the Western Wall? Sorry, my Hebrew is just "shalom".' },
  cp_tourist_me: { speaker: 'me', text: 'Yes. Bag on the belt, please, and walk through the gate.' },
  cp_tourist_wand: { speaker: 'tourist', text: 'Oh, the belt buckle! Sorry, sorry.' },
  cp_tourist_in: { speaker: 'tourist', text: 'Thank you! Shalom, shalom!' },
  cp_knife_1: { speaker: 'visitor', text: 'ערב טוב. עמוס הערב, אה?' },
  cp_knife_open: { speaker: 'visitor', text: 'אה, הסכין? אוי, שכחתי לגמרי. אני חותך איתה תפוחים לילדים.' },
  cp_knife_me: { speaker: 'me', text: 'הסכין נשארת פה. תקבל אותה בחזרה ביציאה.' },
  cp_knife_2: { speaker: 'visitor', text: 'בסדר, בסדר. אתם צודקים. גמר טוב.' },
  cp_family_1: { speaker: 'dad', text: 'ערב טוב! תגיד שלום לחייל, צדיק.' },
  cp_family_kid: { speaker: 'kid', text: 'שלום חייל! תראה, אני יודע להצדיע!' },
  cp_family_in: { speaker: 'dad', text: 'גמר חתימה טובה. בוא, נלך לסבא.' },

  cp_guard_1: { speaker: 'guard', text: 'ערב טוב, חבר׳ה! שמעון, משמרת לילה. אני לוקח מפה.' },
  cp_guard_2: { speaker: 'yonatan', text: 'שמעון! כבר חשבנו ששכחת אותנו.' },
  cp_guard_3: { speaker: 'guard', text: 'שכחתי? עמדתי חצי שעה בתור לקפה. כל ירושלים פה הלילה, גם המוכר.' },
  cp_guard_4: { speaker: 'yonatan', text: 'שים לב לסבתות. אחת מהן כמעט האכילה אותו בכוח.' },
  cp_guard_5: { speaker: 'guard', text: 'אז הוא עבר את המבחן. יאללה, לכו, אני מסתדר.' },
  cp_guard_6: { speaker: 'yonatan', text: 'אני עולה לעמדה שלי בטרסה. אתה לסיור ליד הכותל, ככה ביקש אלון.' },
  cp_guard_7: { speaker: 'cmdRadio', text: 'כאן אלון. סיימתם בבידוק? תתחיל סיור לאורך רחבת התפילה, עד הקשת ובחזרה. תעדכן.', radio: true },

  // Task 2: the patrol near the wall (radio check-ins).
  patrol_1: { speaker: 'meRadio', text: 'קיבלתי, יוצא לסיור.', radio: true },
  patrol_2a: { speaker: 'cmdRadio', text: 'איך זה נראה אצלך?', radio: true },
  patrol_2b: { speaker: 'meRadio', text: 'עמוס אבל רגוע. משפחות, תיירים, הרבה מתפללים.', radio: true },
  patrol_2c: { speaker: 'cmdRadio', text: 'מצוין. תמשיך, ותדבר עם אנשים. שיראו אותנו.', radio: true },
  patrol_3a: { speaker: 'control', text: 'לכל התחנות, מוקד: עדכון קהל. כשלושים אלף ברחבה ובסמטאות, ועוד מגיעים. המשיכו בערנות.', radio: true },
  patrol_4a: { speaker: 'cmdRadio', text: 'נועם, מה המצב אצלך?', radio: true },
  patrol_4b: { speaker: 'noamRadio', text: 'ליד מעלה המוגרבים. שקט, חוץ מסבתא אחת שמחפשת את הנכדים שלה.', radio: true },
  patrol_4c: { speaker: 'cmdRadio', text: 'תעזור לה. כולם, עוד חצי שעה מתחילים. להישאר ערניים.', radio: true },

  // Task 3: the radio call.
  radio_1: { speaker: 'post3', text: 'מוקד, כאן תצפית 3. תנועה חריגה באזור שער האשפות. קבוצה גדולה, לא מאומת.', radio: true },
  radio_2: { speaker: 'control', text: 'תצפית 3, מוקד. קיבלתי, תמשיכו לעקוב ותדווחו.', radio: true },
  radio_3: { speaker: 'cmdRadio', text: 'כל הכיתה, כאן אלון. להתכנס אליי, מרכז הרחבה, ליד המסך. עכשיו.', radio: true },
  gather_1: { speaker: 'cmd', text: 'שמעתם את תצפית 3. אולי זה כלום. אבל יש פה הלילה עשרות אלפי אנשים.' },
  gather_2: { speaker: 'noam', text: 'אם משהו קורה פה הלילה, אין לאן לברוח. כל היציאות פקוקות.' },
  gather_3: { speaker: 'cmd', text: 'בגלל זה מכינים תוכנית: אם יש אזעקה, מכוונים לקשת וילסון, למנהרות וליציאות. בלי פאניקה.' },
  gather_4: { speaker: 'control', text: 'לכל התחנות: דיווחים לא מאומתים על התקהלויות בכמה נקודות בעיר העתיקה.', radio: true },
  radio_5: { speaker: 'yonatan', text: 'זה נשמע לכם רגיל?' },
  radio_6: { speaker: 'post3', text: 'מוקד, תצפית 3... אני רואה אותם עכשיו. הם רצים לכיוון—', radio: true },
  radio_7: { speaker: 'radio', text: '(רעש סטטי)' },
  radio_8: { speaker: 'cmd', text: 'נשארים יחד! זזים!' },

  // ---- Part 2 ----
  // Sirens. Lines with `radio: true` are spoken over the radio (filtered, squelch).
  siren_1: { speaker: 'noam', text: 'זה... צבע אדום? עכשיו, באמצע הסליחות?' },
  siren_2: { speaker: 'cmd', text: 'אזעקה! מפנים את הרחבה, כולם למחסה!' },
  siren_3: { speaker: 'control', text: 'לכל הכוחות ברובע: שיגורים לעבר ירושלים. היכונו לאירוע רב־זירתי.' },
  ready_1: { speaker: 'cmd', text: 'נשק דרוך! מחסנית בפנים, כדור בקנה. מעכשיו זה לא תרגיל.' },
  ready_2: { speaker: 'yonatan', text: 'דרוך!' },
  ready_3: { speaker: 'noam', text: 'דרוך!' },

  // Shelter
  shelter_1: { speaker: 'cmd', text: 'מכוונים את האנשים: לאולם מתחת לקשת וילסון, למנהרות וליציאות! בלי דחיפות!' },
  shelter_2: { speaker: 'cmd', text: 'יש אנשים שקפאו במקום. תגיע אליהם ותזיז אותם, אתה יודע מה לעשות.' },
  shelter_3: { speaker: 'yonatan', text: 'פקק במדרגות! אני מוריד אותם מהטרסה לכיוון הקשת!' },
  shelter_4: { speaker: 'noam', text: 'המפקד, משפחות עם ילדים תקועות ליד הבידוק!' },
  shelter_5: { speaker: 'cmd', text: 'תפתחו להם מעבר. אל תעצרו, להמשיך לזוז!' },
  shelter_late: { speaker: 'control', text: 'לכל התחנות: דיווחים על חמושים בכניסות לעיר העתיקה. היכונו.', radio: true },
  civ_thanks_1: { speaker: 'civilian', text: 'כן, כן, אני הולך!' },
  civ_thanks_2: { speaker: 'civilianWoman', text: 'תודה... לאן? לקשת? בסדר!' },
  civ_thanks_3: { speaker: 'civilian', text: 'אלוהים ישמור. רץ!' },
  civ_thanks_4: { speaker: 'civilianWoman', text: 'הילדים שלי... טוב, אני הולכת!' },

  // First contact
  contact_1: { speaker: 'post3', text: 'מוקד, תצפית 3! חמושים בכניסה הדרומית, יורים!', radio: true },
  contact_2: { speaker: 'cmd', text: 'מגע! כולם למחסה! להחזיק את הרחבה!' },
  contact_south: { speaker: 'noam', text: 'מגע, כניסה דרומית! ליד הבידוק!', radio: true },
  contact_west: { speaker: 'yonatan', text: 'מגע, מדרגות מערביות! עוד חוליה מלמעלה!', radio: true },
  contact_watch: { speaker: 'cmd', text: 'תשמור על שני הכיוונים! דרום ומערב!', radio: true },
  down_1: { speaker: 'yonatan', text: 'נטרלתי אחד!', radio: true },
  down_2: { speaker: 'noam', text: 'מחבל ירד!', radio: true },
  down_3: { speaker: 'cmd', text: 'פגיעה! להמשיך לירות!', radio: true },
  down_player_1: { speaker: 'cmd', text: 'יפה! ירד!', radio: true },
  down_player_2: { speaker: 'noam', text: 'פגיעה טובה!', radio: true },
  last_one: { speaker: 'cmd', text: 'נשאר אחד! לא לתת לו לברוח!', radio: true },

  // After the wave
  after_1: { speaker: 'cmd', text: 'חדל! חדל! מישהו פגוע? תנו לי מצב.' },
  after_2: { speaker: 'yonatan', text: 'אני בסדר. שריטה, לא יותר.' },
  after_3: { speaker: 'noam', text: 'בסדר גמור. האזרחים באולם ובמנהרות, אף אחד לא נפגע.' },
  after_4: { speaker: 'cmd', text: 'מוקד, כאן כיתת הסיור. הדפנו חוליה ראשונה ברחבת הכותל. אין נפגעים.', radio: true },
  after_5: { speaker: 'control', text: 'קיבלתי. תגבורת בדרך, לפחות עשרים דקות. אתם חייבים להחזיק את הרחבה.', radio: true },
  after_6: { speaker: 'cmd', text: 'שמעתם. הם יחזרו, ויותר. מחליפים מחסניות ותופסים עמדות. אנחנו מחזיקים את הכותל.' },

  // ---- Part 3: holding the plaza ----
  def_1: { speaker: 'cmd', text: 'הקו שלנו: החומה הנמוכה בין הרחבה לאזור התפילה. מאחורינו, מתחת לקשת וילסון, מאות אזרחים.' },
  def_2: { speaker: 'cmd', text: 'אף אחד לא עובר את החומה הזאת. יונתן צפון, נועם דרום, אתה איתי באמצע.' },
  def_3: { speaker: 'yonatan', text: 'הבאתי ארגז תחמושת מעמדת המשטרה. מחסניות ורימונים, תתפנקו.' },
  def_4: { speaker: 'noam', text: 'רק תזכרו: הם מגיעים מלמעלה, מהמדרגות המערביות, וגם מהכניסה הדרומית.' },
  prep_1: { speaker: 'cmd', text: 'קחו רימונים. שלושה לכל אחד, לא יותר.' },
  prep_2: { speaker: 'cmd', text: 'ואל תתקבעו במקום אחד. מי שנשאר באותה נקודה, יחטוף רימון.' },
  prep_3: { speaker: 'post3', text: 'כיתת הכותל, כאן תצפית 3. יש תנועה על גג מעל המדרגות המערביות. היכונו.', radio: true },

  wave1_a: { speaker: 'post3', text: 'חמושים יורדים במדרגות המערביות! חמישה, אולי יותר!', radio: true },
  wave1_b: { speaker: 'cmd', text: 'מגע מערב! להחזיק את הקו!' },
  w1_contact: { speaker: 'yonatan', text: 'מגע, מדרגות מערביות! רובאים!', radio: true },
  b1_1: { speaker: 'cmd', text: 'חדל! להחליף מחסניות. מי שחסר לו, לארגז.' },
  b1_2: { speaker: 'noam', text: 'זה היה רק הגל הראשון, נכון?' },
  b1_3: { speaker: 'control', text: 'כיתת הכותל, מוקד. אנחנו רואים שתי קבוצות מתארגנות: מערב ודרום.', radio: true },

  wave2_a: { speaker: 'post3', text: 'שתי חוליות! אחת במדרגות, אחת בכניסה הדרומית, יחד!', radio: true },
  wave2_b: { speaker: 'cmd', text: 'שני כיוונים! נועם, תחזיק את הדרום!' },
  w2_stairs: { speaker: 'yonatan', text: 'מגע, מדרגות! הם יורים אש חיפוי, תשארו נמוכים!', radio: true },
  w2_flank: { speaker: 'yonatan', text: 'הם מאגפים לאורך הקצה הצפוני של הרחבה!', radio: true },
  w2_south: { speaker: 'noam', text: 'מגע, דרום! אחד מהם זז לאורך החפירות, מאגף!', radio: true },
  over_1: { speaker: 'noam', text: 'הם מעל החומה בצד הצפוני! הקו נפרץ!', radio: true },
  over_2: { speaker: 'cmd', text: 'נסיגה! לעמדה השנייה ליד הכותל, מול הקשת! זזים, זזים!' },
  p2_1: { speaker: 'cmd', text: 'זאת העמדה האחרונה. מאחורינו הקשת והאזרחים. מכאן לא זזים.' },
  p2_2: { speaker: 'yonatan', text: 'עוד ארגז פה, ליד הקיר. תמלאו.' },
  p2_3: { speaker: 'post3', text: 'כיתת הכותל... הם מביאים הכול. כולל צלף על הטרסות העליונות.', radio: true },

  wave3_a: { speaker: 'control', text: 'לכל התחנות: מתקפה גדולה על רחבת הכותל, מכל הכיוונים!', radio: true },
  wave3_b: { speaker: 'cmd', text: 'הנה הם באים! כל מה שיש לכם!' },
  w3_sniper: { speaker: 'yonatan', text: 'צלף על הטרסות העליונות! תחפשו את הנצנוץ של הכוונת!', radio: true },
  w3_stairs: { speaker: 'noam', text: 'מגע, מדרגות! הרבה!', radio: true },
  w3_rush: { speaker: 'noam', text: 'הם רצים עלינו מהדרום! להסתער אלינו!', radio: true },
  grenade_1: { speaker: 'yonatan', text: 'רימון!' },
  grenade_2: { speaker: 'noam', text: 'רימון! תתרחקו!' },
  grenade_3: { speaker: 'cmd', text: 'רימון! לזוז!' },

  lull_1: { speaker: 'cmd', text: 'חדל... הם נסוגים. תנו לי מצב.' },
  lull_2: { speaker: 'yonatan', text: 'אני בסדר. כמעט בלי תחמושת.' },
  lull_3: { speaker: 'post3', text: 'מוקד, תצפית 3. הם מתארגנים בשער האשפות. עשרות, ויש רכבים.', radio: true },
  lull_4: { speaker: 'control', text: 'קיבלתי. כיתת הכותל, זה הולך להיות גדול יותר. תגבורת עדיין בדרך.', radio: true },
  lull_5: { speaker: 'noam', text: 'יותר גדול מזה?' },
  lull_6: { speaker: 'cmd', text: 'למלא מחסניות, לשתות מים. כשהם יחזרו, אנחנו כאן.' },

  // ---- Part 4: the final push, the counterattack, the ending ----
  final_1: { speaker: 'post3', text: 'הם יוצאים! מכל הכיוונים: מדרגות, דרום, צפון, גגות!', radio: true },
  final_2: { speaker: 'cmd', text: 'זה זה. המתקפה האחרונה שלהם. אף אחד לא עובר!' },
  truck_1: { speaker: 'noam', text: 'רכב! טנדר עם מקלע פרץ בכניסה הדרומית!', radio: true },
  truck_2: { speaker: 'yonatan', text: 'הוא מרתק אותנו! אני לא יכול להרים את הראש!', radio: true },
  truck_3: { speaker: 'cmd', text: 'רובים לא יעשו לו כלום! קח את המטול מארגז התחמושת, עכשיו!' },
  truck_4: { speaker: 'cmd', text: 'יש לך מטול. תכוון לטנדר ותוריד אותו!' },
  truck_hit: { speaker: 'noam', text: 'הוא עוד זז! עוד טיל!', radio: true },
  truck_down_1: { speaker: 'cmd', text: 'הטנדר מושמד! פגיעה מושלמת!' },
  truck_down_2: { speaker: 'yonatan', text: 'הם נסוגים! הם בורחים לבידוק ולמדרגות!', radio: true },

  counter_1: { speaker: 'cmd', text: 'מעכשיו אנחנו תוקפים. לוקחים את הרחבה בחזרה!' },
  counter_2: { speaker: 'cmd', text: 'מתקדמים בדילוגים: חוליה אחת מחפה, השנייה זזה. יעד ראשון: הבידוק הדרומי.' },
  move_1: { speaker: 'yonatan', text: 'זז!', radio: true },
  move_2: { speaker: 'noam', text: 'מתקדם!', radio: true },
  cover_1: { speaker: 'cmd', text: 'מחפה!', radio: true },
  cover_2: { speaker: 'yonatan', text: 'מחפה, לך!', radio: true },
  cp_1: { speaker: 'cmd', text: 'הבידוק נקי! הבידוק הדרומי בידינו!' },
  cp_2: { speaker: 'noam', text: 'יש עוד חוליה על המדרגות המערביות, הם יורים מלמעלה.' },
  cp_3: { speaker: 'cmd', text: 'אז עולים אליהם. יעד שני: המדרגות המערביות.' },
  stairs_done: { speaker: 'yonatan', text: 'המדרגות נקיות! אין יותר תנועה!' },

  end_1: { speaker: 'control', text: 'כיתת הכותל, כאן מוקד. כוחות תגבורת נכנסים לעיר העתיקה מכל השערים.', radio: true },
  end_2: { speaker: 'control', text: 'המחבלים שנותרו נמלטים. אתם יכולים להוריד את הראש. עבודה טובה.', radio: true },
  end_3: { speaker: 'cmd', text: 'שמעתם. חדל אש. נאסף ליד הכותל.' },
  end_4: { speaker: 'noam', text: 'תראו... האזרחים יוצאים מהקשת.' },
  end_5: { speaker: 'guide', text: 'הם החזיקו. הם באמת החזיקו.' },
  end_6: { speaker: 'yonatan', text: 'אמא שלי לא תאמין לסיפור הזה בסעודה המפסקת.' },
  end_7: { speaker: 'cmd', text: 'הלילה שמרנו על המקום הזה, ועל האנשים שבו. זה מה שאנחנו. גמר חתימה טובה.' },

  // ---- The Selichot crowd (story/people.js) ----
  // Greetings when the player walks by.
  greet_man_1: { speaker: 'man', text: 'גמר חתימה טובה!' },
  greet_man_2: { speaker: 'man', text: 'גמר חתימה טובה, חייל. תודה שאתם פה.' },
  greet_man_3: { speaker: 'man', text: 'חזק וברוך! גמר חתימה טובה.' },
  greet_woman_1: { speaker: 'woman', text: 'גמר חתימה טובה. שמרו על עצמכם.' },
  greet_woman_2: { speaker: 'woman', text: 'גמר חתימה טובה, מתוק.' },
  greet_visitor_1: { speaker: 'visitor', text: 'כל הכבוד לכם, גמר טוב!' },
  greet_visitor_2: { speaker: 'visitor', text: 'גמר חתימה טובה, אחי.' },
  greet_visitorF_1: { speaker: 'visitorF', text: 'גמר טוב! תודה שאתם שומרים עלינו.' },
  greet_dad_1: { speaker: 'dad', text: 'תגידו גמר חתימה טובה לחייל, ילדים.' },
  greet_mom_1: { speaker: 'mom', text: 'גמר חתימה טובה. תודה לכם.' },
  greet_elder_1: { speaker: 'elder', text: 'גמר חתימה טובה, בני.' },
  greet_grandma_1: { speaker: 'grandma', text: 'גמר חתימה טובה, מותק. אכלת משהו?' },
  greet_kid_1: { speaker: 'kid', text: 'חייל! גמר חתימה טובה!' },
  greet_kidGirl_1: { speaker: 'kidGirl', text: 'שלום חייל!' },
  greet_teen_1: { speaker: 'teen', text: 'אחי, גמר טוב.' },
  greet_tourist_1: { speaker: 'tourist', text: 'Shalom! Thank you for your service!' },
  greet_touristWoman_1: { speaker: 'touristWoman', text: 'Shalom! Stay safe tonight.' },
  greet_yeshiva_1: { speaker: 'yeshiva', text: 'גמר חתימה טובה! בהצלחה במשמרת.' },
  greet_usher_1: { speaker: 'usher', text: 'ערב טוב, גמר חתימה טובה!' },
  greet_police_1: { speaker: 'police', text: 'ערב טוב. עמוס הערב, אה?' },
  greet_soldierVisitor_1: { speaker: 'soldierVisitor', text: 'אחי, גמר טוב. משמרת ארוכה?' },
  collector_ask_1: { speaker: 'collector', text: 'צדקה תציל ממוות! צדקה!' },
  collector_ask_2: { speaker: 'collector', text: 'מי שנותן הלילה, נחתם לטובה!' },

  // E: a short exchange that fits who they are ([their line, your reply, ...]).
  ex_man_1: { speaker: 'man', text: 'עוד מעט הסליחות הגדולות. כשכל הרחבה עונה "אמן" ביחד, זה מרעיד.' },
  ex_man_1r: { speaker: 'me', text: 'נשמע מרגש. גמר חתימה טובה.' },
  ex_man_2: { speaker: 'man', text: 'תגיד, כמה אנשים יש פה הלילה? נראה לי יותר משנה שעברה.' },
  ex_man_2r: { speaker: 'me', text: 'הרבה. הלילה הכי עמוס בשנה.' },
  ex_woman_1: { speaker: 'woman', text: 'התפללתי גם עליכם, על החיילים. גמר חתימה טובה.' },
  ex_woman_1r: { speaker: 'me', text: 'תודה רבה. גמר טוב.' },
  ex_woman_2: { speaker: 'woman', text: 'הבן שלי גם בצבא, בגבעתי. תשמרו על עצמכם, כן?' },
  ex_woman_2r: { speaker: 'me', text: 'נשמור. שיחזור בשלום.' },
  ex_visitor_1: { speaker: 'visitor', text: 'תגיד, מאיפה רואים הכי טוב את המסך? באנו לסליחות של חצות.' },
  ex_visitor_1r: { speaker: 'me', text: 'מהרחבה, מול המסכים. רק תגיעו מוקדם, מתמלא.' },
  ex_visitor_2: { speaker: 'visitor', text: 'וואו, מה זה האנשים הערב. אתם בכלל ישנים?' },
  ex_visitor_2r: { speaker: 'me', text: 'אחרי כיפור.' },
  ex_visitorF_1: { speaker: 'visitorF', text: 'באנו בסיור סליחות מתל אביב. אף פעם לא ראיתי את הכותל בלילה, זה מטורף.' },
  ex_visitorF_1r: { speaker: 'me', text: 'תיהני. ותישארו עם הקבוצה, עמוס פה.' },
  ex_visitorF_2: { speaker: 'visitorF', text: 'סליחה, יש פה שירותים איפשהו?' },
  ex_visitorF_2r: { speaker: 'me', text: 'מאחור, ליד המדרגות של הרובע.' },
  ex_dad_1: { speaker: 'dad', text: 'אנחנו באים כל שנה, מאז שהגדול היה בגיל שלו. עכשיו הגדול בצבא.' },
  ex_dad_1r: { speaker: 'me', text: 'שיהיה בהצלחה לו. גמר טוב.' },
  ex_mom_1: { speaker: 'mom', text: 'סליחה, ראית ילד קטן בחולצה כחולה? אה, הנה הוא. תודה!' },
  ex_elder_1: { speaker: 'elder', text: 'בני, אני בא לכאן כבר שישים שנה. ראיתי את המקום הזה כשהיה סמטה צרה.' },
  ex_elder_1r: { speaker: 'me', text: 'וואו. גמר חתימה טובה, סבא.' },
  ex_grandma_1: { speaker: 'grandma', text: 'אכלת משהו? אתה רזה מדי. יש לי עוגת דבש בתיק.' },
  ex_grandma_1r: { speaker: 'me', text: 'תודה, סבתא, אני בסדר.' },
  ex_kid_1: { speaker: 'kid', text: 'אתה חייל אמיתי? כמה זמן אתה כבר חייל?' },
  ex_kid_1r: { speaker: 'me', text: 'שנתיים. ואתה תהיה חייל טוב, אני רואה.' },
  ex_kidGirl_1: { speaker: 'kidGirl', text: 'אבא אמר שאתם שומרים על כולנו.' },
  ex_kidGirl_1r: { speaker: 'me', text: 'נכון. ואת תשמרי על אבא, בסדר?' },
  ex_teen_1: { speaker: 'teen', text: 'אחי, ראית קבוצה של בני עקיבא? הלכתי לאיבוד.' },
  ex_teen_1r: { speaker: 'me', text: 'תשאל את הסדרנים בכניסה, הם מכירים את כולם.' },
  ex_tourist_1: { speaker: 'tourist', text: 'Excuse me, is it true the prayers start at midnight?' },
  ex_tourist_1r: { speaker: 'me', text: 'Yes, at midnight. Find a spot early.' },
  ex_touristWoman_1: { speaker: 'touristWoman', text: 'Sorry, where do women go to the wall?' },
  ex_touristWoman_1r: { speaker: 'me', text: 'The women\'s section is on the right, past the partition.' },
  ex_yeshiva_1: { speaker: 'yeshiva', text: 'אחי, רוצה לשמוע דבר תורה קצר על סליחות?' },
  ex_yeshiva_1r: { speaker: 'me', text: 'אחרי המשמרת, אחי.' },
  ex_yeshiva_2: { speaker: 'yeshiva', text: 'אני תופס אותך במילה!' },
  ex_usher_1: { speaker: 'usher', text: 'כיפה? אה, אתה עם כומתה. טוב, גמר חתימה טובה.' },
  ex_usher_1r: { speaker: 'me', text: 'עמוס אצלכם?' },
  ex_usher_2: { speaker: 'usher', text: 'מאז שבע בערב. חילקתי כבר שלושה ארגזים.' },
  ex_collector_1: { speaker: 'collector', text: 'צדקה תציל ממוות! תרומה קטנה, חייל?' },
  ex_collector_1r: { speaker: 'me', text: 'אין לי ארנק במשמרת.' },
  ex_collector_2: { speaker: 'collector', text: 'אז ברכה במקום כסף: שתחזור הביתה בשלום!' },
  ex_guide_1: { speaker: 'guide', text: 'אני מביאה קבוצה כל שנה לסליחות של לפני כיפור. אין עוד לילה כזה.' },
  ex_guide_1r: { speaker: 'me', text: 'בהצלחה עם הקבוצה.' },
  ex_police_1: { speaker: 'police', text: 'אני פה מהשעה שש. עוד לא ראיתי כזה עומס.' },
  ex_police_1r: { speaker: 'me', text: 'גם בבידוק היה טירוף.' },
  ex_soldierVisitor_1: { speaker: 'soldierVisitor', text: 'אני מגולני, באתי עם החבר׳ה לסליחות. אתם במשמרת כל הלילה?' },
  ex_soldierVisitor_1r: { speaker: 'me', text: 'כל הלילה. תיהנו, ותשאירו עיניים פתוחות.' },
  ex_guard_1: { speaker: 'guard', text: 'הכול בסדר? לילה ארוך.' },
  ex_guard_1r: { speaker: 'me', text: 'לילה ארוך.' },

  // Special people: longer exchanges.
  sp_bless_1: { speaker: 'elder', text: 'בוא הנה, בני. תוריד רגע את הראש.' },
  sp_bless_2: { speaker: 'me', text: 'כן, סבא?' },
  sp_bless_3: { speaker: 'elder', text: '"יברכך ה׳ וישמרך. יאר ה׳ פניו אליך ויחונך. ישא ה׳ פניו אליך וישם לך שלום."' },
  sp_bless_4: { speaker: 'elder', text: 'שתחזור הביתה בשלום. גמר חתימה טובה.' },
  sp_bless_5: { speaker: 'me', text: 'אמן. תודה, סבא.' },
  sp_salute_1: { speaker: 'kid', text: 'חייל! חייל! תראה, אני יודע להצדיע!' },
  sp_salute_2: { speaker: 'me', text: 'וואו, הצדעה של מפקד. כל הכבוד!' },
  sp_salute_3: { speaker: 'kid', text: 'כשאהיה גדול אני אהיה בדיוק כמוך!' },
  sp_salute_4: { speaker: 'dad', text: 'בוא, צדיק, תן לחייל לעבוד.' },
  sp_snack_1: { speaker: 'visitor', text: 'אחי, קח במבה. קח!' },
  sp_snack_2: { speaker: 'me', text: 'תודה, באמת, אני בסדר.' },
  sp_snack_3: { speaker: 'visitor', text: 'אני לא שואל. אתה עומד פה כל הלילה, אתה חייב לאכול משהו.' },
  sp_snack_4: { speaker: 'me', text: 'טוב, טוב. תודה.' },
  sp_snack_5: { speaker: 'visitor', text: 'ככה אני אוהב. גמר חתימה טובה!' },
  sp_notes_1: { speaker: 'tourist', text: 'Excuse me, soldier, what are all these little papers in the wall?' },
  sp_notes_2: { speaker: 'me', text: 'Notes. People write prayers and put them in the cracks.' },
  sp_notes_3: { speaker: 'tourist', text: 'Anyone can do it? Even me?' },
  sp_notes_4: { speaker: 'me', text: 'Anyone. Twice a year they collect them and bury them on the Mount of Olives.' },
  sp_notes_5: { speaker: 'tourist', text: 'Wow. Then I need a pen!' },
  sp_photo_1: { speaker: 'visitorF', text: 'סליחה, אפשר תמונה איתך? זה בשביל אבא שלי, הוא היה בגולני.' },
  sp_photo_2: { speaker: 'me', text: 'בטח, רק מהר.' },
  sp_photo_3: { speaker: 'visitorF', text: 'אחת, שתיים... חיוך!' },
  sp_photo_4: { speaker: 'visitorF', text: 'תודה! הוא ישמח. גמר חתימה טובה!' },
};

export const OBJECTIVES = {
  screening: 'בידוק בכניסה: בדוק את הנכנסים',
  screen_wait: 'בידוק: חכה לשמעון המאבטח',
  patrol: 'סיור לאורך רחבת התפילה',
  patrol_more: 'המשך לסייר ליד הכותל (דבר עם אנשים, E)',
  gather: 'היאסף עם הכיתה במרכז הרחבה',
  report: 'דווח למפקד הכיתה',
  follow_cmd: 'הישאר עם המפקד',
  patrol_wall: 'סיור עם הכיתה: אזור התפילה ליד הכותל',
  patrol_terraces: 'סיור עם הכיתה: הטרסות העליונות',
  wait_orders: 'הישאר עם הכיתה',
  take_cover: 'הישאר עם המפקד',
  shelter: 'הבא את האזרחים למחסה מתחת לקשת וילסון',
  eliminate: 'חסל את המחבלים',
  regroup: 'התארגנו מחדש עם הכיתה',
  take_position: 'תפוס עמדה בחומה הנמוכה מול הרחבה',
  hold_line: 'החזק את הקו: אל תתן להם להגיע לאזרחים',
  fall_back: 'היסוג לעמדה השנייה ליד הכותל',
  hold_line2: 'החזק את העמדה השנייה',
  final_hold: 'עצור את המתקפה האחרונה',
  get_launcher: 'קח את המטול מארגז התחמושת',
  destroy_truck: 'השמד את הטנדר עם המקלע',
  secure_checkpoint: 'כבוש את הבידוק הדרומי',
  secure_stairs: 'כבוש את המדרגות המערביות',
  regroup_wall: 'היאסף עם הכיתה ליד הכותל',
};

// The security checkpoint: what's in the bags (and in pockets: the hand detector finds it).
export const SCREEN_ITEMS = {
  siddur: 'סידור',
  tallit: 'שקית טלית',
  bottle: 'בקבוק מים',
  phone: 'טלפון',
  charger: 'מטען וכבל',
  camera: 'מצלמה',
  map: 'מפה של העיר העתיקה',
  pot: 'סיר קוגל',
  box: 'קופסת רוגלך',
  pitas: 'פיתות',
  thermos: 'תרמוס תה',
  cake: 'עוגת דבש',
  knife: 'סכין מתקפלת',
  wallet: 'ארנק',
  snacks: 'במבה וביסלי',
  toy: 'מכונית צעצוע',
  keys: 'צרור מפתחות בכיס',
  buckle: 'אבזם חגורה',
};

// Counter shown under the objective (a number follows).
export const COUNTERS = {
  screened: 'נבדקו',
  civilians: 'אזרחים שנותרו בחוץ',
  enemies: 'מחבלים שנותרו',
};

// Hints show a key and a text; keys stay LTR. `touch`: the text on a phone or tablet (the
// on-screen controls, no keys shown).
export const HINTS = {
  move: { keys: ['W', 'A', 'S', 'D'], text: 'תנועה, והעכבר להסתכלות', touch: 'ג׳ויסטיק בצד שמאל לתנועה, גרירה בצד ימין להסתכלות' },
  talk: { keys: ['E'], text: 'שיחה', touch: 'הקישו על כפתור השיחה' },
  screen: { keys: ['E', 'F'], text: 'הסתכל על המסך, התיק והאדם · E פעולה · F עצירה / החרמה', touch: 'הסתכלו על המסך, התיק והאדם, והקישו על הפעולה או על עצירה / החרמה' },
  people: { keys: ['E'], text: 'שיחה עם אנשים ברחבה', touch: 'הסתכלו על אדם ברחבה והקישו על כפתור השיחה' },
  sprint: { keys: ['Shift'], text: 'החזק לריצה', touch: 'דחפו את הג׳ויסטיק עד הסוף קדימה לריצה' },
  crouch: { keys: ['C'], text: 'התכופפות', touch: 'כפתור ההתכופפות' },
  mag: { keys: ['R'], text: 'בדיקת מחסנית (הנשק מונמך במשמרת)', touch: 'כפתור הטעינה: בדיקת מחסנית (הנשק מונמך במשמרת)' },
  shelter: { keys: ['E'], text: 'ליד אזרח שקפא: שלח אותו למחסה', touch: 'ליד אזרח שקפא: הקישו כדי לשלוח אותו למחסה' },
  fire: { keys: ['LMB', 'RMB'], text: 'ירי / כוונת', touch: 'כפתור הירי, וכפתור הכוונת להפעלה ולכיבוי' },
  grenade: { keys: ['G'], text: 'רימון: החזק לכיוון, שחרר לזריקה', touch: 'רימון: החזיקו את הכפתור לכיוון, שחררו לזריקה' },
  switch: { keys: ['1', '2'], text: 'החלפת נשק (או גלגלת העכבר). כוונת עם המקש הימני.', touch: 'כפתור החלפת הנשק' },
};

export const CARDS = {
  intro: ['הכותל המערבי, ירושלים', '21:00', 'ליל הסליחות האחרון לפני יום כיפור'],
  part1End: ['סוף חלק 1', 'המשך יבוא'],
  part3End: ['להחזיק את הכותל', 'המשך יבוא'],
  mission2Soon: ['משימה 2', 'בקרוב'],
};

// Mission UI text.
export const STORY_UI = {
  objectivePrefix: 'משימה',
  meters: 'מ׳',
  talkPrompt: 'שיחה עם',
  screen: {
    monitor: 'מסך שיקוף',
    open: 'פתח את התיק',
    wand: 'סרוק בגלאי ידני',
    letIn: 'הכנס',
    stop: 'עצור',
    confiscate: 'החרם את הסכין',
    beep: 'השער צפצף',
    clear: 'השער נקי',
    contents: 'בתיק',
    wandFound: 'הגלאי הידני מצא',
    taken: 'הסכין הוחרמה. תוחזר ביציאה.',
    xrayNote: 'כתום: אורגני · ירוק: מעורב · כחול: מתכת',
  },
  shelterPrompt: 'שלח למחסה',
  cratePrompt: 'ארגז תחמושת: מלא מחסניות ורימונים',
  crateLauncherPrompt: 'ארגז תחמושת: קח את המטול',
  missionComplete: 'המשימה הושלמה',
  missionName: 'משימה 1: הכותל',
  stats: { time: 'זמן', accuracy: 'דיוק', headshots: 'פגיעות ראש', kills: 'מחבלים שנוטרלו' },
  weaponRifle: 'רובה סער',
  weaponLauncher: 'מטול',
  resupplied: 'תחמושת ורימונים מולאו',
  lowAmmo: 'תחמושת נמוכה: לך לארגז התחמושת',
  failedTitle: 'המשימה נכשלה',
  failedCivilian: 'פגעת באזרח.',
  failedTeammate: 'פגעת בחבר צוות.',
  retry: 'חוזרים לנקודת השמירה האחרונה…',
  checkpoint: 'נקודת שמירה',
  devMenuTitle: 'כלי פיתוח: קפיצה לשלב במשימה',
  devWeapon: 'נשק דרוך (לבדיקה)',
  devClose: 'סגירה (F2)',
};
