// All player-facing text (Hebrew, RTL). Keep UI strings here, not in logic code.

export const HE = {
  gameTitle: 'משחק הכותל',
  missionName: 'משימה 1 · הכותל',
  weapons: { rifle: 'רובה סער', launcher: 'מטול רקטות' }, // generic names (no real models or brands)
  graphics: { title: 'איכות גרפיקה', low: 'נמוכה', medium: 'בינונית', high: 'גבוהה', ultra: 'אולטרה' },
  lockError: 'לא הצלחנו לנעול את העכבר. חכו רגע ולחצו שוב.',

  // Loading screen: a line about the Kotel while the game loads (facts: docs/kotel-reference.md).
  loading: {
    title: 'טוען…',
    done: 'לחצו בכל מקום כדי להמשיך',
    facts: [
      'הכותל המערבי הוא חלק מחומת התמך שבנה הורדוס סביב הר הבית, לפני כ־2,000 שנה.',
      'ברחבת התפילה נראים כ־57 מטרים מתוך כ־488 המטרים של החומה המערבית. רובה מוסתר מאחורי בתים ובמנהרות הכותל.',
      'לכותל 45 נדבכי אבן: 28 מעל פני הרחבה ו־17 מתחתיה, עד הסלע.',
      'שבעת הנדבכים התחתונים שנראים לעין הם מימי הורדוס: אבנים ענקיות, מסותתות בשוליים, מונחות בלי טיט.',
      'האבן הגדולה הידועה בכותל, "האבן המערבית", ארוכה כ־13.6 מטרים. היא נמצאת במנהרות הכותל, צפונית לקשת וילסון.',
      'קשת וילסון, בצפון רחבת התפילה, נשאה בימי הבית השני דרך אל הר הבית.',
      'אחרי מלחמת ששת הימים, ב־1967, נפתחה הרחבה של היום, ורצפתה הונמכה בכשני מטרים.',
      'הפתקים שבין אבני הכותל נאספים פעמיים בשנה ונקברים בהר הזיתים.',
      'צמחי צלף צומחים בין האבנים בנדבכים העליונים של הכותל.',
    ],
  },

  menu: {
    continue: 'המשך',
    continueFrom: (chapter) => `מ${chapter}`,
    newGame: 'משחק חדש',
    settings: 'הגדרות',
    credits: 'קרדיטים',
    quit: 'יציאה',
    back: 'חזרה',
    hint: 'עכבר או חיצים ו־Enter · Esc לחזרה',
    // New game: the difficulty, then the start or a chapter.
    newGameTitle: 'משחק חדש',
    difficulty: 'רמת קושי',
    startFromTop: 'התחל מההתחלה',
    chapters: 'או התחילו מחלק במשימה',
    overwrite: 'משחק חדש יחליף את ההתקדמות השמורה. להמשיך?',
    yes: 'כן',
    no: 'לא',
  },

  pause: {
    title: 'המשחק מושהה',
    resume: 'חזרה למשחק',
    restart: 'התחלה מנקודת הביקורת',
    settings: 'הגדרות',
    quitToMenu: 'יציאה לתפריט הראשי',
    confirmRestart: 'לחזור לנקודת הביקורת האחרונה? מה שקרה מאז יאבד.',
    confirmQuit: 'לצאת לתפריט הראשי? ההתקדמות נשמרת בנקודת הביקורת האחרונה.',
    missionDone: 'המשימה הושלמה',
  },

  settings: {
    title: 'הגדרות',
    tabs: { controls: 'שליטה', graphics: 'גרפיקה', audio: 'שמע', gameplay: 'משחק' },
    sensitivity: 'רגישות עכבר',
    lookSensitivity: 'רגישות מבט',
    aimSensitivity: 'רגישות בכינון',
    invertY: 'היפוך ציר אנכי',
    bindingsTitle: 'מקשים',
    bindingsHint: 'לחצו על מקש כדי לשנות אותו, ואז הקישו את המקש החדש (Esc לביטול).',
    pressKey: 'הקישו מקש…',
    resetKeys: 'מקשי ברירת מחדל',
    fixedKeys: 'מקשים קבועים',
    quality: 'איכות גרפיקה',
    qualityHint: 'בינונית: 60 פריימים בשנייה במחשב נייד ממוצע. גבוהה: במחשב גיימינג בינוני. בחירת רמה מאפסת את המתגים למטה.',
    effectsTitle: 'אפקטים',
    effectsHint: 'כל אפקט אפשר להדליק או לכבות בנפרד, מעל רמת האיכות.',
    effects: {
      aa: 'החלקת קצוות זמנית (TAA)',
      motionBlur: 'טשטוש תנועה',
      ao: 'הצללה סביבתית (AO)',
      contactShadows: 'צללי מגע',
      ssgi: 'אור מוחזר (GI)',
      ssr: 'השתקפויות באבן',
      dof: 'עומק שדה (בכינון ובשיחות)',
      eyeAdaptation: 'הסתגלות העין לאור',
      bloom: 'הילות אור',
      lensFlare: 'השתקפויות עדשה',
      grain: 'גרעיניות סרט',
      vignette: 'הכהיית שוליים',
      haze: 'אובך ואלומות אור',
      heat: 'רעד אוויר חם',
      parallax: 'עומק באבני הכותל',
      detail: 'פרטים ובלאי באבן',
      dynamicRes: 'רזולוציה דינמית',
    },
    motionBlurLevels: { off: 'כבוי', low: 'נמוך', high: 'גבוה' },
    fov: 'שדה ראייה',
    showFps: 'מונה פריימים',
    volume: { master: 'עוצמה ראשית', music: 'מוזיקה', sfx: 'אפקטים', voice: 'דיבור' },
    difficulty: 'רמת קושי',
    difficultyLevels: { easy: 'קל', normal: 'רגיל', hard: 'קשה' },
    difficultyHint: {
      easy: 'האויבים מגיבים לאט יותר, מכוונים פחות טוב ופוגעים חלש יותר.',
      normal: 'החוויה כפי שתוכננה.',
      hard: 'האויבים מהירים, מדויקים וקטלניים יותר, וזורקים יותר רימונים.',
    },
    subtitles: 'כתוביות',
    on: 'פועל',
    off: 'כבוי',
  },

  // Rebindable actions (core/Bindings.js), in the order they're listed.
  actions: {
    forward: 'קדימה',
    back: 'אחורה',
    left: 'שמאלה',
    right: 'ימינה',
    jump: 'קפיצה',
    sprint: 'ריצה (להחזיק)',
    crouch: 'התכופפות',
    fire: 'ירי',
    aim: 'כינון בכוונת',
    reload: 'החלפת מחסנית',
    grenade: 'רימון (להחזיק, לשחרר לזריקה)',
    interact: 'שיחה / פעולה',
    deny: 'עצירה / החרמה (בבידוק)',
    weapon1: 'רובה',
    weapon2: 'מטול',
  },
  // Keys that can't be changed.
  fixedControls: [
    { keys: ['Esc'], label: 'השהיה ותפריט' },
    { keys: ['גלגלת'], label: 'החלפת נשק' },
    { keys: ['`'], label: 'נתוני ביצועים' },
    { keys: ['P'], label: 'צילום מסך' },
  ],

  creditsScreen: {
    hint: 'Esc או לחיצה לחזרה',
    software: 'תוכנה',
    license: 'רישיון',
  },

  sensitivity: 'רגישות עכבר',
  fps: 'FPS',
  screenshot: {
    savedTo: 'צילום המסך נשמר:',
    downloaded: 'צילום המסך נשמר בתיקיית ההורדות',
  },
  death: {
    title: 'נהרגת',
    subtitle: 'חוזרים לנקודת ההתחלה…',
  },
  enemyState: {
    idle: 'רגוע',
    alerted: 'חשדן',
    combat: 'קרב',
    dead: 'מת',
  },
  enemyMode: {
    none: '',
    moving: 'רץ למחסה',
    hiding: 'מסתתר',
    peeking: 'מציץ ויורה',
    exposed: 'חשוף',
  },
  ammo: {
    reloading: 'מחליף מחסנית…',
    reloadHint: 'R להחלפת מחסנית',
    empty: 'אין תחמושת',
  },
  hud: {
    fps: 'FPS',
    speed: 'מהירות',
    metersPerSecond: 'מ׳/ש׳',
    height: 'גובה',
    meters: 'מ׳',
    grounded: 'על הקרקע',
    airborne: 'באוויר',
    standing: 'עמידה',
    crouching: 'התכופפות',
    sprinting: 'ריצה',
    drawCalls: 'קריאות ציור',
    health: 'בריאות',
    enemies: 'אויבים',
    kills: 'הריגות',
  },
};
