// All player-facing text (Hebrew, RTL). Keep UI strings here, not in logic code.

export const HE = {
  gameTitle: 'משחק הכותל',
  buildLabel: 'אב־טיפוס · שלב 3: רחבת הכותל',
  start: 'לחצו כדי להתחיל',
  resume: 'לחצו כדי להמשיך',
  paused: 'המשחק מושהה',
  lockError: 'לא הצלחנו לנעול את העכבר. חכו רגע ולחצו שוב.',
  controlsTitle: 'שליטה',
  controls: [
    { keys: ['W', 'A', 'S', 'D'], label: 'תנועה' },
    { keys: ['עכבר'], label: 'הסתכלות' },
    { keys: ['לחיצה שמאלית'], label: 'ירי (להחזיק לאוטומטי)' },
    { keys: ['לחיצה ימנית'], label: 'כינון בכוונת' },
    { keys: ['R'], label: 'החלפת מחסנית' },
    { keys: ['רווח'], label: 'קפיצה' },
    { keys: ['Shift'], label: 'ריצה (להחזיק)' },
    { keys: ['C'], label: 'התכופפות (הפעלה / ביטול)' },
    { keys: ['Esc'], label: 'השהיה' },
    { keys: ['`'], label: 'נתוני ביצועים' },
  ],
  sensitivity: 'רגישות עכבר',
  ammo: {
    reloading: 'מחליף מחסנית…',
    reloadHint: 'R להחלפת מחסנית',
    empty: 'אין תחמושת',
  },
  hud: {
    fps: 'FPS',
    speed: 'מהירות',
    metersPerSecond: 'מ׳/ש׳',
    height: 'גובה',
    meters: 'מ׳',
    grounded: 'על הקרקע',
    airborne: 'באוויר',
    standing: 'עמידה',
    crouching: 'התכופפות',
    sprinting: 'ריצה',
    drawCalls: 'קריאות ציור',
  },
};
