// All player-facing text (Hebrew, RTL). Keep UI strings here, not in logic code.

export const HE = {
  gameTitle: 'משחק הכותל',
  buildLabel: 'אב־טיפוס · שלב 4: אויב ראשון',
  start: 'לחצו כדי להתחיל',
  chaptersTitle: 'או התחילו מחלק מסוים',
  weapons: { rifle: 'M4', launcher: 'מטול רקטות' },
  graphics: { title: 'איכות גרפיקה', low: 'נמוכה', medium: 'בינונית', high: 'גבוהה' },
  resume: 'לחצו כדי להמשיך',
  paused: 'המשחק מושהה',
  lockError: 'לא הצלחנו לנעול את העכבר. חכו רגע ולחצו שוב.',
  controlsTitle: 'שליטה',
  controls: [
    { keys: ['W', 'A', 'S', 'D'], label: 'תנועה' },
    { keys: ['עכבר'], label: 'הסתכלות' },
    { keys: ['לחיצה שמאלית'], label: 'ירי (להחזיק לאוטומטי)' },
    { keys: ['לחיצה ימנית'], label: 'כינון בכוונת' },
    { keys: ['R'], label: 'החלפת מחסנית' },
    { keys: ['רווח'], label: 'קפיצה' },
    { keys: ['Shift'], label: 'ריצה (להחזיק)' },
    { keys: ['C'], label: 'התכופפות (הפעלה / ביטול)' },
    { keys: ['G'], label: 'רימון (להחזיק לכיוון, לשחרר לזריקה)' },
    { keys: ['1', '2'], label: 'החלפת נשק (גם גלגלת העכבר)' },
    { keys: ['E'], label: 'שיחה / פעולה / ארגז תחמושת' },
    { keys: ['Esc'], label: 'השהיה' },
    { keys: ['`'], label: 'נתוני ביצועים' },
    { keys: ['F1'], label: 'כלי פיתוח: מצב אויבים, ראייה, מחסות, ניווט' },
    { keys: ['K'], label: 'הוספת אויב' },
    { keys: ['F2'], label: 'כלי פיתוח: קפיצה לשלב במשימה' },
  ],
  sensitivity: 'רגישות עכבר',
  death: {
    title: 'נהרגת',
    subtitle: 'חוזרים לנקודת ההתחלה…',
  },
  enemyState: {
    idle: 'רגוע',
    alerted: 'חשדן',
    combat: 'קרב',
    dead: 'מת',
  },
  enemyMode: {
    none: '',
    moving: 'רץ למחסה',
    hiding: 'מסתתר',
    peeking: 'מציץ ויורה',
    exposed: 'חשוף',
  },
  ammo: {
    reloading: 'מחליף מחסנית…',
    reloadHint: 'R להחלפת מחסנית',
    empty: 'אין תחמושת',
  },
  hud: {
    fps: 'FPS',
    speed: 'מהירות',
    metersPerSecond: 'מ׳/ש׳',
    height: 'גובה',
    meters: 'מ׳',
    grounded: 'על הקרקע',
    airborne: 'באוויר',
    standing: 'עמידה',
    crouching: 'התכופפות',
    sprinting: 'ריצה',
    drawCalls: 'קריאות ציור',
    health: 'בריאות',
    enemies: 'אויבים',
    kills: 'הריגות',
  },
};
